nietz/app/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^game/(?P<pk>[0-9]+)/$', views.game_detail, name='game_detail'),
        url(r'^categorylist/$', views.categorylist, name='categorylist'),
        url(r'^rolllist/$', views.rolllist, name='rolllist'),
        url(r'^unstar/$', views.unstar, name='unstar'),
        url(r'^star/$', views.star, name='star'),
        url(r'^category/$', views.category, name='category'),
        url(r'^game/$', views.game, name='game'),
]

nietz/nietz/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'nietz.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'app.views.index', name='index'),
    url(r'^app/', include('app.urls', namespace='app')) # do not forget this
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns('',
                (r'^img/(?P<path>.*)$',
                'django.views.static.serve',
                {'document_root': settings.MEDIA_ROOT})
                )

nietz/app/models.py
# encoding=utf-8
from django.db import models
from django_thumbs.db.models import ImageWithThumbsField

# Create your models here.

class Category(models.Model):
    name = models.CharField(unique=True, max_length=255, verbose_name=u"分类名")
    ctime = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'category'
        ordering = ['-ctime']
        verbose_name = u"游戏类别"

    def __unicode__(self):
        return self.name


class Game(models.Model):
    name = models.CharField(max_length=255, verbose_name=u"游戏名")
    download = models.CharField(max_length=255, verbose_name=u"下载地址")
    # logo = models.ImageField(upload_to='logo')
    logo = ImageWithThumbsField(upload_to='thumbs', sizes=((40, 40), (140, 140)), verbose_name=u"Logo标志图")
    rotation = ImageWithThumbsField(upload_to='rotation', sizes=((800, 200), ), verbose_name=u"轮播图")
    active = models.BooleanField(default=False, verbose_name=u"是否轮播")
    category = models.ForeignKey(Category, verbose_name="游戏分类")
    ctime = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'game'
        ordering = ['-ctime']
        verbose_name = u"游戏"

    def __unicode__(self):
        return self.name

nietz/app/forms.py
#!/usr/bin/env python
# encoding: utf-8
from django import forms
from app.models import Category
from app.models import Game
from django.conf import settings


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', ]


class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        exclude = ['ctime']

    def clean(self):
        cleaned_data = super(GameForm, self).clean()
        active_flag = cleaned_data.get("active")
        if active_flag:
            rotation_num = getattr(settings, "ROTATION_NUM", 5)
            db_active_num = Game.objects.filter(active=True).count()
            if db_active_num >= rotation_num:
                # raise  forms.ValidationError(u"轮播图数量已经达到上限。") non field error
                msg = u"轮播图数量已经达到上限。"
                self.add_error("active", msg)
        return cleaned_data

nietz/app/views.py
# encoding=utf-8
from django.shortcuts import render
from .models import Game
from .models import Category
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.http import  HttpResponseRedirect
from django.http import  HttpResponse
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from .forms import CategoryForm
from .forms import GameForm
from django.core.urlresolvers import reverse
import json


def index(request):
    page_num = getattr(settings, 'PAGE_MAX_NUM', 5)
    games = Game.objects.all()
    paginator = Paginator(games, page_num)
    page = request.GET.get('page')
    rotations = [game for game in games if game.active]
    try:
        games = paginator.page(page)
    except PageNotAnInteger:
        games = paginator.page(1)
    except EmptyPage:
        games = paginator.page(paginator.num_pages)
    content = {"games": games, "rotations": rotations}
    return render(request, 'app/index.html', content)


def categorylist(request):
	categories = Category.objects.all()
	return render(request, 'app/categorylist.html', {"categories": categories})


# rotation game list
def rolllist(request):
	rotations = Game.objects.filter(active=True)
	return render(request, 'app/rolllist.html', {"rotations": rotations})


def star(request):
    rotation_num = getattr(settings, "ROTATION_NUM", 5)
    if 'g_id' in request.POST:
        g_id = int(request.POST['g_id'])
        game = get_object_or_404(Game, pk=g_id)
        if not game.active:
            current_num = Game.objects.filter(active=True).count()
            if current_num >= rotation_num:
                result = {"msg": u"已经达到数量上限，无法增加轮播游戏。", "error": 1}
            else:
                game.active = True
                game.save()
                result = {"msg": u"成功添加轮播游戏。", "error": 0}
        return HttpResponse(json.dumps(result))


def unstar(request):
	if 'g_id' in request.POST:
		g_id = int(request.POST['g_id'])
		game = get_object_or_404(Game, pk=g_id)
		if game.active:
			game.active = False
			game.save()
			result = {"msg": u"成功取消轮播游戏。", "error": 0}
			return HttpResponse(json.dumps(result))


def  category(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/app/categorylist/")
    else:
        form = CategoryForm()
    return render(request, 'app/category.html', {"form": form})


def game(request):
    if request.method == "POST":
        form = GameForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/app/")
    else:
        form = GameForm()
    return render(request, 'app/game.html', {"form": form})


def game_detail(request, pk):
	game = get_object_or_404(Game, pk=pk)
	return render(request, 'app/game_detail.html', {"game": game})

nietz/app/templates/app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{STATIC_URL}}favicon.ico">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bp/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    {% block extrastyle %}{% endblock %}


    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extrahead %}{% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
		  data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">游戏管理</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">

            <li><a href="#">chyoo</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class=""><a href="/">游戏列表<span class="sr-only"></span></a></li>
            <li><a href="{% url 'app:categorylist' %}">分类列表</a></li>
            <li><a href="{% url 'app:rolllist' %}">轮播图表</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="{% url 'app:game' %}">添加游戏</a></li>
            <li><a href="{% url 'app:category' %}">添加分类</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            {% block maincontent %}{% endblock %}

        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bp/js/bootstrap.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

    {% block extrajs %}{% endblock %}
  </body>
</html>

nietz/app/templates/app/category.html
{% extends "app/base.html" %}

{% block title %} 添加分类 {% endblock %}

{% block maincontent %}

<form class="form-horizontal" method="post" action=".">
  {% csrf_token %}

  {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}


  <div class="form-group">
    <label for="id_name" class="col-sm-2 control-label">分类名</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="id_name" name="name" placeholder="分类名">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">提交</button>
    </div>
  </div>
</form>


{% endblock %}

nietz/app/templates/app/categorylist.html
{% extends "app/base.html" %}

{% block title %}游戏分类{% endblock %}

{% block maincontent %}

<h2 class="sub-header">游戏分类列表</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>编号</th>
                  <th>名称</th>
		     <th>创建时间</th>
                </tr>
              </thead>
              <tbody>
	      {% if categories %}
		{% for c in categories %}
                <tr>
                  <th>{{ forloop.counter }}</th>
                  <th>{{ c.name }}</th>
		  <th>{{ c.ctime }}</th>
                </tr>
                {% endfor %}
              {% endif %}
              </tbody>
            </table>
          </div>

{% endblock %}

nietz/app/templates/app/game.html
{% extends "app/base.html" %}

{% block title %} 添加游戏 {% endblock %}

{% block maincontent %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    <strong>提交失败，请纠正下面的错误。</strong>
</div>
{% endif %}

<form class="form-horizontal" method="post"  action="" enctype="multipart/form-data">
  {% csrf_token %}


  <div class="form-group">
    <label class="col-sm-2 control-label" for="id_name">游戏名</label>

    <div class="col-sm-4">
        {{ form.name }}
    </div>
    {% if form.name.errors %}
      <div class="col-sm-4">
          <div class="alert alert-danger" role="alert">{{ form.name.errors }}</div>
      </div>
  {% endif %}
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label" for="id_donwload">下载地址</label>

    <div class="col-sm-4">
        {{ form.download }}
    </div>

    {% if form.download.errors %}
    <div class="col-sm-4">
            <div class="alert alert-danger" role="alert">{{ form.download.errors }}</div>
    </div>
   {% endif %}

  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label" for="id_logo">游戏Logo</label>

    <div class="col-sm-4">
        {{ form.logo }}
    </div>

    {% if form.logo.errors %}
    <div class="col-sm-4">
           <div class="alert alert-danger" role="alert">{{ form.logo.errors }}</div>
   </div>
  {% endif %}
</div>

  <div class="form-group">
    <label class="col-sm-2 control-label" for="id_rotation">轮播图</label>

    <div class="col-sm-4">
        {{ form.rotation }}
    </div>
      {% if form.rotation.errors %}
      <div class="col-sm-4">
        <div class="alert alert-danger" role="alert">{{ form.rotation.errors }}</div>
      </div>
    {% endif %}
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label" for="id_active">是否轮播图</label>

    <div class="col-sm-4">
        {{ form.active }}
    </div>
    {% if form.active.errors %}
      <div class="col-sm-4">
            <div class="alert alert-danger" role="alert">{{ form.active.errors }}</div>
      </div>
   {% endif %}
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label" for="id_category">游戏类别</label>

    <div class="col-sm-4">
        {{ form.category }}
    </div>
    {% if form.category.errors %}
    <div class="col-sm-4">
             <div class="alert alert-danger" role="alert">{{ form.category.errors }}</div>
    </div>
  {% endif %}
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">提交</button>
    </div>
  </div>

</form>

{% endblock %}

nietz/app/templates/app/game_detail.html
{% extends "app/base.html"  %}

{% block title %} 游戏信息 {% endblock %}

{% block maincontent %}

<h2 class="sub-header">游戏信息</h2>
<dl class="dl-horizontal">
  <dt>游戏名</dt>
  <dd>{{ game.name }} </dd>


  <dt>Logo</dt>
  <dd><div class="row">
  <div class="col-xs-3 col-md-3">
    <a href="{{ game.logo.url }}" class="thumbnail">
      <img src="{{ game.logo.url }}">
    </a>
  </div>
</div>
</dd>

 <dt>轮播图</dt>
  <dd><div class="row">
  <div class="col-xs-8 col-md-3">
    <a href="{{ game.rotation.url }}" class="thumbnail">
      <img src="{{ game.rotation.url_800x200 }}">
    </a>
  </div>
</div>
</dd>

  <dt>下载地址</dt>
  <dd>{{ game.download }}</dd>

 <dt>分类</dt>
 <dd>{{ game.category }}</dd>

 <dt>创建时间</dt>
 <dd>{{ game.ctime }}</dd>

 </dl>

{% endblock %}

nietz/app/templates/app/index.html
{% extends "app/base.html"  %}
{% load staticfiles %}
{% block title %} Game Manage {% endblock %}

{% block maincontent %}

		<div id="myCarousel" class="carousel slide">
		  <ol class="carousel-indicators">
		    {% for _ in rotations %}
		    <li data-target="#myCarousel" data-slide-to="{{ forloop.counter }}" {% if forloop.first %} class="active" {% endif %}></li>
		    {% endfor %}
		  </ol>
		  <!-- Carousel items -->
		  <div class="carousel-inner">
		    {% if rotations %}
			{% for game in rotations %}
			   {% if game.active %}
				<div class="{% if forloop.first %}active{% endif %} item"><img src="{{ game.rotation.url_800x200 }}"></div>
			   {% endif %}
			{%endfor%}
			{% endif %}
		  </div>
		  <!-- Carousel nav -->
		  <a class="carousel-control left" href="#myCarousel" data-slide="prev"></a>
		  <a class="carousel-control right" href="#myCarousel" data-slide="next"></a>
		</div>
          <h2 class="sub-header">游戏列表</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>编号</th>
		  <th>logo</th>
                  <th>名称</th>
                  <th>类别</th>

                  <th>轮播图</th>
		     <th>下载地址</th>
				 <th> 创建时间</th>
		     <th>操作</th>
                </tr>
              </thead>
              <tbody>
	      {% if games %}
		{% for game in games %}
                <tr>
                  <th>{{ forloop.counter }}</th>
		  <th><img src="{{ game.logo.url_40x40 }}" class="img-rounded"></th>
                  <th><a href="{% url 'app:game_detail' game.id %}">{{ game.name }}</a></th>
                  <th>{{ game.category }}</th>
                  <th>{% if game.active %}  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> {% else %}
                                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> {% endif %}</th>
		  <th>{{ game.download }}</th>
			<th>{{ game.ctime }}</th>
		  <th>{% if game.active %} <button type="button" class="btn-danger btn btn-sm unstar" id="{{ game.id }}">unstar</button>
		          {% else %} <button type="button" class="btn-info btn btn-sm star" id="{{ game.id }}" >star</button>
		          {% endif %}</th>
                </tr>
                {% endfor %}
              {% endif %}
              </tbody>
            </table>
          </div>
				<nav>
						  <ul class="pager">
								{% if games.has_previous %}
						    <li class="previous"><a href="?page={{ games.previous_page_number }}"><span aria-hidden="true">&larr;</span> 上一页</a></li>
								{% else %}
								  <li class="previous disabled"><a href="#"><span aria-hidden="true">&larr;</span> 上一页</a></li>
								{% endif %}

								{% if games.has_next %}
								<li class="next"><a href="?page={{ games.next_page_number }}"><span aria-hidden="true">&rarr;</span> 下一页</a></li>
								{% else %}
									<li class="next disabled"><a href="#"><span aria-hidden="true">&rarr;</span> 下一页</a></li>
								{% endif %}
						  </ul>
			  </nav>
{% endblock %}

{% block extrajs %}
<script src="{% static 'js/star.js' %}"></script>
{% endblock %}

nietz/app/templates/app/rolllist.html
{% extends "app/base.html" %}
{% load staticfiles %}
{% block title %} 轮播图列表 {% endblock %}

{% block maincontent %}

<h2 class="sub-header">轮播图列表</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>编号</th>
                  <th>logo</th>
                  <th>名称</th>
                  <th>类别</th>
                  <th>下载地址</th>
                  <th>操作</th>
                </tr>
              </thead>
              <tbody>
              {% if rotations %}
                 {% for game in rotations %}
                <tr>
                  <th>{{ forloop.counter }}</th>
                  <th><img src="{{ game.logo.url_40x40 }}" class="img-rounded"></th>
                  <th><a href="{% url 'app:game_detail' game.id %}">{{ game.name }}</a></th>
                  <th>{{ game.category }}</th>
                  <th>{{ game.download }}</th>
                  <th><button type="button" class="btn btn-danger btn-sm unstar" id="{{ game.id }}" >Unstar</button></th>
                </tr>
                {% endfor %}
              {% endif %}
              </tbody>
            </table>
          </div>
{% endblock %}

{% block extrajs %}
<script src="{% static 'js/star.js' %}"></script>
{% endblock %}

nietz/app/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Game Manage</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bp/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">游戏管理</a>		
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">

            <li><a href="#">chyoo</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">游戏列表<span class="sr-only">(current)</span></a></li>
            <li><a href="#">分类列表</a></li>
            <li><a href="#">轮播图表</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">添加游戏</a></li>
            <li><a href="">添加分类</a></li>
            <li><a href="">设置轮播图</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">


		<div id="myCarousel" class="carousel slide">
		  <ol class="carousel-indicators">
		    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		    <li data-target="#myCarousel" data-slide-to="1"></li>
		    <li data-target="#myCarousel" data-slide-to="2"></li>
		  </ol>
		  <!-- Carousel items -->
		  <div class="carousel-inner">
		    {% if rotations %}
			{% for game in rotations %}
			   {% if game.active %}
				<div class="{% if forloop.first %}active{% endif %} item"><img src="{{ game.rotation.url_800x200 }}"></div>
			   {% endif %}
			{%endfor%}
		    
                    {% endif %}
		  </div>
		  <!-- Carousel nav -->
		  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
		  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
		</div>


          <h2 class="sub-header">游戏列表</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>ID</th>
		  <th>logo</th>
                  <th>名称</th>
                  <th>类别</th>
                  
                  <th>是否轮播图</th>
		  <th>下载地址</th>
                </tr>
              </thead>
              <tbody>
	      {% if games %}
		{% for game in games %}
                <tr>
                  <th>{{ game.id }}</th>
		  <th><img src="{{ game.logo.url_40x40 }}" class="img-rounded"></th>
                  <th>{{ game.name }}</th>
                  <th>{{ game.category }}</th>
                  <th>{% if game.active %}  <span class="glyphicon glyphicon-star" aria-hidden="true"></span> {% else %}
                                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> {% endif %}</th>
		  <th>{{ game.download }}</th>
                </tr>
                {% endfor %}
              {% endif %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bp/js/bootstrap.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>